### ISSUE TITLE
Описание переменных окружения в .env

### ISSUE THREAD

**Issue by bonefabric** [nekromant322/TwitchMentorBot#20]
Предлагаю переменные окружения для docker-compose хранить в файле конфигурации .env, который не должен попадать в репозиторий, а в качестве шаблона добавить файл .env.example. При установке необходимо скопировать .env.example => .env и заменить переменные своими данными. Docker-compose поддерживает такой подход: https://docs.docker.com/compose/environment-variables/set-environment-variables/

**Comment by bonefabric** [comment]
Вся работа в настройке переменных окружения после клонирования репозитория будет в том, чтобы скопировать env.example, который хранит все ключи для перменных окружения, в свой приватный .env и указание своии значения.
Кроме того пропадает привязка к ide.

Подход к хранию переменных окружения в специальном файле практикуется широко:
- Node.js: https://nodejs.dev/en/learn/how-to-read-environment-variables-from-nodejs/
- Laravel https://laravel.com/docs/10.x/configuration#environment-configuration
- Python: https://github.com/theskumar/python-dotenv (6к завезд)

В общем тема крутая, запряги кого-то

**Comment by nekromant322** [comment]
Храним енвы в хранилище сикретов  
локально запускаем с кайфом в отдельном профиле
